{% set name = "gwpopulation-pipe" %}
{% set version = "0.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwpopulation_pipe-{{ version }}.tar.gz
  sha256: 66cb18a649e485c5239811ff9075111cc88f07b253a9ec6ac92a39cf26f7cd1f

build:
  entry_points:
    - gwpopulation_pipe=gwpopulation_pipe.main:main
    - gwpopulation_pipe_analysis=gwpopulation_pipe.data_analysis:main
    - gwpopulation_pipe_collection=gwpopulation_pipe.data_collection:main
    - gwpopulation_pipe_plot=gwpopulation_pipe.post_plots:main
    - gwpopulation_pipe_pp_test=gwpopulation_pipe.review:setup_pp_test
    - gwpopulation_pipe_simulate_posteriors=gwpopulation_pipe.data_simulation:main
    - gwpopulation_pipe_to_common_format=gwpopulation_pipe.common_format:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools
    - setuptools_scm
    - pip
    - python {{ python_min }}
  run:
    - astropy-base
    - bilby >=2.3.0
    - bilby_pipe >=1.3.0
    - dynesty >2.0.0
    - extension-helpers
    - gwpopulation >=1.1.0
    - h5py
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - python-htcondor
    - scipy
    - tqdm
    - wcosmo

test:
  imports:
    - gwpopulation_pipe
  commands:
    - pip install popsummary
    - pip check
    - gwpopulation_pipe --help
    - gwpopulation_pipe_analysis --help
    - gwpopulation_pipe_collection --help
    - gwpopulation_pipe_plot --help
    - gwpopulation_pipe_pp_test --help
    - gwpopulation_pipe_simulate_posteriors --help
    - gwpopulation_pipe_to_common_format --help
  requires:
    - python {{ python_min }}
    - pip
    - scipy <1.15

about:
  home: https://git.ligo.org/RatesAndPopulations/gwpopulation_pipe
  summary: A pipeline population inference
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
