{% set name = "gwpopulation-pipe" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwpopulation_pipe-{{ version }}.tar.gz
  sha256: 81224eac22d0472f18faf0a71da360f5feb9549876b095bc6e635ac076e44955

build:
  entry_points:
    - gwpopulation_pipe=gwpopulation_pipe.main:main
    - gwpopulation_pipe_analysis=gwpopulation_pipe.data_analysis:main
    - gwpopulation_pipe_collection=gwpopulation_pipe.data_collection:main
    - gwpopulation_pipe_plot=gwpopulation_pipe.post_plots:main
    - gwpopulation_pipe_pp_test=gwpopulation_pipe.review:setup_pp_test
    - gwpopulation_pipe_simulate_posteriors=gwpopulation_pipe.data_simulation:main
    - gwpopulation_pipe_to_common_format=gwpopulation_pipe.common_format:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - astropy
    - bilby >=2.3.0
    - bilby_pipe
    - deepdish
    - dynesty >2.0.0
    - extension-helpers
    - gwpopulation >=1.1.0
    - h5py
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy
    - tqdm

test:
  imports:
    - gwpopulation_pipe
  commands:
    - pip check
    - gwpopulation_pipe --help
    - gwpopulation_pipe_analysis --help
    - gwpopulation_pipe_collection --help
    - gwpopulation_pipe_plot --help
    - gwpopulation_pipe_pp_test --help
    - gwpopulation_pipe_simulate_posteriors --help
    - gwpopulation_pipe_to_common_format --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.ligo.org/RatesAndPopulations/gwpopulation_pipe
  summary: A pipeline population inference
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
